name: medicine_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0-49.0.dev

# Add regular dependencies here.
dependencies:
  # Database
  drift: ^2.28.1
  sqlite3: ^2.8.0
  path: ^1.9.0

  # server on Dart
  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.4
  shelf_router_generator: ^1.1.1
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  # code generation
  build_runner: ^2.6.0

  # Database
  drift_dev: ^2.28.1

  # Lints
  lints: ^6.0.0

  # Testing
  test: ^1.25.6
